theme: jekyll-theme-hacker
title: Chandan's Log
description: My collection of useful developer info & insights 
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - java/java9_features.md
  - java/java10_features.md
  - java/collections.md
  - scala/forcomp.md
  - scala/hkt.md
  - security/openssl_commands.md
